#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Artisan Console Application
|--------------------------------------------------------------------------
|
| This file is the entry point for the Laravel Artisan console application.
| It is loaded by Composer's bin-dir directive in composer.json.
|
*/

define('LARAVEL_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
));
