<?php
\=chr(39);
\=chr(10);
\="C:/laragon/www/procurement/resources/views";
\=[];


// ===== VIEW 1: inventory/adjust.blade.php =====
$v1 = [];
$v1[] = "@extends(".$q."layouts.app".$q.")";
$v1[] = "";
$v1[] = "@section(".$q."content".$q.")";
$v1[] = "<div class=\"max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8\">";
$v1[] = "";
$v1[] = "    {{-- Page Header --}}";
$v1[] = "    <div class=\"mb-6\">";
$v1[] = "        <div class=\"flex flex-col sm:flex-row sm:items-center sm:justify-between\">";
$v1[] = "            <div>";
$v1[] = "                <h1 class=\"text-3xl font-bold text-gray-900\">";
$v1[] = "                    Stock Adjustment &mdash; {{ \->name ?? ".$q."N/A".$q." }}";
$v1[] = "                </h1>";
$v1[] = "                <p class=\"mt-1 text-sm text-gray-600\">Record a manual adjustment to the current stock level.</p>";
$v1[] = "            </div>";
$v1[] = "            <div class=\"mt-4 sm:mt-0\">";
$v1[] = "                <a href=\"{{ route(".$q."inventory.show".$q.", \->id) }}\"";
$v1[] = "                   class=\"inline-flex items-center px-4 py-2 rounded-md bg-gray-200 text-gray-700 hover:bg-gray-300 transition-colors\">";
$v1[] = "                    Back to Item";
$v1[] = "                </a>";
$v1[] = "            </div>";
$v1[] = "        </div>";
$v1[] = "    </div>";

$v1[] = "";
$v1[] = "    @if(session(".$q."success".$q."))";
$v1[] = "    <div class=\"mb-6 rounded-lg bg-green-50 border border-green-200 p-4 flex items-start gap-3\">";
$v1[] = "        <svg class=\"h-5 w-5 text-green-500 mt-0.5 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">";
$v1[] = "            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z\"/>";
$v1[] = "        </svg>";
$v1[] = "        <p class=\"text-sm text-green-800\">{{ session(".$q."success".$q.") }}</p>";
$v1[] = "    </div>";
$v1[] = "    @endif";
$v1[] = "    @if(session(".$q."error".$q."))";
$v1[] = "    <div class=\"mb-6 rounded-lg bg-red-50 border border-red-200 p-4 flex items-start gap-3\">";
$v1[] = "        <svg class=\"h-5 w-5 text-red-500 mt-0.5 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">";
$v1[] = "            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"/>";
$v1[] = "        </svg>";
$v1[] = "        <p class=\"text-sm text-red-800\">{{ session(".$q."error".$q.") }}</p>";
$v1[] = "    </div>";
$v1[] = "    @endif";

$v1[] = "";
$v1[] = "    {{-- Current Stock Info Card --}}";
$v1[] = "    <div class=\"bg-white rounded-lg shadow p-6 mb-6\">";
$v1[] = "        <h2 class=\"text-base font-semibold text-gray-900 mb-4\">Current Stock Information</h2>";
$v1[] = "        <dl class=\"grid grid-cols-2 sm:grid-cols-4 gap-4\">";
$v1[] = "            <div>";
$v1[] = "                <dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Item Code</dt>";
$v1[] = "                <dd class=\"mt-1 text-sm font-mono font-semibold text-primary-700\">{{ \->item_code ?? ".$q."N/A".$q." }}</dd>";
$v1[] = "            </div>";
$v1[] = "            <div>";
$v1[] = "                <dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Item Name</dt>";
$v1[] = "                <dd class=\"mt-1 text-sm text-gray-900 font-medium\">{{ \->name ?? ".$q."N/A".$q." }}</dd>";
$v1[] = "            </div>";
$v1[] = "            <div>";
$v1[] = "                <dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Current Qty</dt>";
$v1[] = "                <dd class=\"mt-1 text-sm font-bold text-gray-900\">";
$v1[] = "                    {{ \->quantity_on_hand ?? 0 }}";
$v1[] = "                    <span class=\"text-xs font-normal text-gray-500\">{{ \->unit_of_measure ?? ".$q."".$q." }}</span>";
$v1[] = "                </dd>";
$v1[] = "            </div>";
$v1[] = "            <div>";
$v1[] = "                <dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Store</dt>";
$v1[] = "                <dd class=\"mt-1 text-sm text-gray-900\">{{ \->store?->store_name ?? ".$q."N/A".$q." }}</dd>";
$v1[] = "            </div>";
$v1[] = "        </dl>";
$v1[] = "    </div>";

$v1[] = "";
$v1[] = "    {{-- Adjustment Form --}}";
$v1[] = "    <div class=\"bg-white rounded-lg shadow p-6\">";
$v1[] = "        <h2 class=\"text-base font-semibold text-gray-900 mb-6\">Adjustment Details</h2>";
$v1[] = "        <form method=\"POST\" action=\"{{ route(".$q."inventory.adjustment.store".$q.", \->id) }}\" class=\"space-y-5\">";
$v1[] = "            @csrf";
$v1[] = "            <div>";
$v1[] = "                <label for=\"adjustment_type\" class=\"block text-sm font-medium text-gray-700 mb-1\">Adjustment Type <span class=\"text-red-500\">*</span></label>";
$v1[] = "                <select id=\"adjustment_type\" name=\"adjustment_type\"";
$v1[] = "                        class=\"w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 @error(".$q."adjustment_type".$q.") border-red-400 @enderror\"";
$v1[] = "                        required>";
$v1[] = "                    <option value=\"\">-- Select Type --</option>";
$v1[] = "                    <option value=\"increase\" {{ old(".$q."adjustment_type".$q.") === ".$q."increase".$q." ? ".$q."selected".$q." : ".$q."".$q." }}>Add (Increase Stock)</option>";
$v1[] = "                    <option value=\"decrease\" {{ old(".$q."adjustment_type".$q.") === ".$q."decrease".$q." ? ".$q."selected".$q." : ".$q."".$q." }}>Remove (Decrease Stock)</option>";
$v1[] = "                    <option value=\"correction\" {{ old(".$q."adjustment_type".$q.") === ".$q."correction".$q." ? ".$q."selected".$q." : ".$q."".$q." }}>Set (Correction / Physical Count)</option>";
$v1[] = "                </select>";
$v1[] = "                @error(".$q."adjustment_type".$q.")";
$v1[] = "                    <p class=\"mt-1 text-xs text-red-600\">{{ \ }}</p>";
$v1[] = "                @enderror";
$v1[] = "            </div>";

$v1[] = "            <div>";
$v1[] = "                <label for=\"quantity_delta\" class=\"block text-sm font-medium text-gray-700 mb-1\">Quantity <span class=\"text-red-500\">*</span></label>";
$v1[] = "                <input type=\"number\" id=\"quantity_delta\" name=\"quantity_delta\"";
$v1[] = "                       value=\"{{ old(".$q."quantity_delta".$q.") }}\"";
$v1[] = "                       min=\"0\" step=\"1\"";
$v1[] = "                       class=\"w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 @error(".$q."quantity_delta".$q.") border-red-400 @enderror\"";
$v1[] = "                       placeholder=\"Enter quantity\" required>";
$v1[] = "                <p class=\"mt-1 text-xs text-gray-500\">For Add/Remove, enter units to add or subtract. For Set, enter the new absolute quantity.</p>";
$v1[] = "                @error(".$q."quantity_delta".$q.")";
$v1[] = "                    <p class=\"mt-1 text-xs text-red-600\">{{ \ }}</p>";
$v1[] = "                @enderror";
$v1[] = "            </div>";
$v1[] = "            <div>";
$v1[] = "                <label for=\"reason\" class=\"block text-sm font-medium text-gray-700 mb-1\">Reason / Justification <span class=\"text-red-500\">*</span></label>";
$v1[] = "                <textarea id=\"reason\" name=\"reason\" rows=\"3\"";
$v1[] = "                          class=\"w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500 @error(".$q."reason".$q.") border-red-400 @enderror\"";
$v1[] = "                          placeholder=\"Provide a clear reason for this adjustment (minimum 10 characters)\"";
$v1[] = "                          required>{{ old(".$q."reason".$q.") }}</textarea>";
$v1[] = "                @error(".$q."reason".$q.")";
$v1[] = "                    <p class=\"mt-1 text-xs text-red-600\">{{ \ }}</p>";
$v1[] = "                @enderror";
$v1[] = "            </div>";
$v1[] = "            <div>";
$v1[] = "                <label for=\"reference\" class=\"block text-sm font-medium text-gray-700 mb-1\">Reference Number</label>";
$v1[] = "                <input type=\"text\" id=\"reference\" name=\"reference\"";
$v1[] = "                       value=\"{{ old(".$q."reference".$q.") }}\"";
$v1[] = "                       class=\"w-full rounded-md border-gray-300 shadow-sm focus:border-primary-500 focus:ring-primary-500\"";
$v1[] = "                       placeholder=\"e.g. ADJ-2026-001 or physical count sheet number\">";
$v1[] = "            </div>";
$v1[] = "            <div class=\"flex items-center justify-end gap-3 pt-4 border-t border-gray-100\">";
$v1[] = "                <a href=\"{{ route(".$q."inventory.show".$q.", \->id) }}\"";
$v1[] = "                   class=\"inline-flex items-center px-4 py-2 rounded-md bg-gray-200 text-gray-700 hover:bg-gray-300 transition-colors\">Cancel</a>";
$v1[] = "                <button type=\"submit\"";
$v1[] = "                        class=\"inline-flex items-center px-5 py-2 rounded-md bg-primary-600 text-white hover:bg-primary-700 transition-colors font-medium\">Record Adjustment</button>";
$v1[] = "            </div>";
$v1[] = "        </form>";
$v1[] = "    </div>";
$v1[] = "";
$v1[] = "</div>";
$v1[] = "@endsection";
file_put_contents($b."/inventory/adjust.blade.php", implode($nl, $v1));


// ===== VIEW 2: inventory/issue.blade.php =====
$v2 = [];
$v2[] = "@extends(".$q."layouts.app".$q.")";
$v2[] = "@section(".$q."content".$q.")";
$v2[] = "<div class=\"max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8\">";
$v2[] = "    <div class=\"mb-6\">";
$v2[] = "        <div class=\"flex flex-col sm:flex-row sm:items-center sm:justify-between\">";
$v2[] = "            <div>";
$v2[] = "                <h1 class=\"text-3xl font-bold text-gray-900\">Issue Stock &mdash; {{ \->name ?? ".$q."N/A".$q." }}</h1>";
$v2[] = "                <p class=\"mt-1 text-sm text-gray-600\">Issue stock from the store to a person or department.</p>";
$v2[] = "            </div>";
$v2[] = "            <div class=\"mt-4 sm:mt-0\">";
$v2[] = "                <a href=\"{{ route(".$q."inventory.show".$q.", \->id) }}\" class=\"inline-flex items-center px-4 py-2 rounded-md bg-gray-200 text-gray-700 hover:bg-gray-300 transition-colors\">Back to Item</a>";
$v2[] = "            </div>";
$v2[] = "        </div>";
$v2[] = "    </div>";
$v2[] = "    @if(session(".$q."success".$q."))";
$v2[] = "    <div class=\"mb-6 rounded-lg bg-green-50 border border-green-200 p-4\"><p class=\"text-sm text-green-800\">{{ session(".$q."success".$q.") }}</p></div>";
$v2[] = "    @endif";
$v2[] = "    @if(session(".$q."error".$q."))";
$v2[] = "    <div class=\"mb-6 rounded-lg bg-red-50 border border-red-200 p-4\"><p class=\"text-sm text-red-800\">{{ session(".$q."error".$q.") }}</p></div>";
$v2[] = "    @endif";
$v2[] = "    <div class=\"bg-white rounded-lg shadow p-6 mb-6\">";
$v2[] = "        <h2 class=\"text-base font-semibold text-gray-900 mb-4\">Current Stock Information</h2>";
$v2[] = "        <dl class=\"grid grid-cols-2 sm:grid-cols-4 gap-4\">";
$v2[] = "            <div><dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Item Code</dt><dd class=\"mt-1 text-sm font-mono font-semibold text-primary-700\">{{ \->item_code ?? ".$q."N/A".$q." }}</dd></div>";
$v2[] = "            <div><dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Item Name</dt><dd class=\"mt-1 text-sm text-gray-900 font-medium\">{{ \->name ?? ".$q."N/A".$q." }}</dd></div>";
$v2[] = "            <div><dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Available Qty</dt><dd class=\"mt-1 text-sm font-bold text-gray-900\">{{ \->quantity_on_hand ?? 0 }} <span class=\"text-xs font-normal text-gray-500\">{{ \->unit_of_measure ?? ".$q."".$q." }}</span></dd></div>";
$v2[] = "            <div><dt class=\"text-xs font-medium text-gray-500 uppercase tracking-wide\">Store</dt><dd class=\"mt-1 text-sm text-gray-900\">{{ \->store?->store_name ?? ".$q."N/A".$q." }}</dd></div>";
$v2[] = "        </dl>";
$v2[] = "    </div>";
